name: GLFW_RELEASES_WATCHER
on:
  schedule:
    - cron:  0 1 1 * *
jobs:
  check_releases:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Fetch latest glfw
        run: |
          echo LATEST_GLFW_VERSION=$(curl -sL https://api.github.com/repos/glfw/glfw/releases/latest | jq -r ".tag_name") >> $GITHUB_ENV
          echo CURRENT_GLFW_VERSION=$(grep -F -m1 "glfwVersion=" gradle.properties | tr -d "glfwVersion=" | tr -d "\"") >> $GITHUB_ENV

      - name: Patch gradle.properties file
        if: env.CURRENT_GLFW_VERSION != env.LATEST_GLFW_VERSION
        uses: christian-draeger/write-properties@1.0.1
        with:
          path: gradle.properties
          property: glfwVersion
          value: ${{ env.LATEST_GLFW_VERSION }}

      - name: Commit & push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        if: env.CURRENT_GLFW_VERSION != env.LATEST_GLFW_VERSION
        with:
          commit_message: Update glfwVersion to ${{ env.LATEST_GLFW_VERSION }}
          token: ${{ env.GH_PAT }}